# This is a comment
FROM mikeduvall/service-base
MAINTAINER Mike DuVall <mike.a.duvall@gmail.com>


WORKDIR /app

ADD gs-spring-boot-0.1.0.jar /app/

EXPOSE 8080

CMD ["java",  "-jar",  "gs-spring-boot-0.1.0.jar"]

